[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Редиректы для SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Настройки для тестовой ветки
[context.mobile-responsive-test]
  command = "npm run build"
  
[context.mobile-responsive-test.environment]
  NODE_ENV = "development"
